// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleAppsScriptType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Slides add-on manifest.
public struct SlidesAddOnManifest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// If present, this overrides the configuration from
  /// `addOns.common.homepageTrigger`.
  public var homepageTrigger: GoogleAppsScriptType.HomepageExtensionPoint? = nil

  /// Endpoint to execute when file scope authorization is granted
  /// for this document/user pair.
  public var onFileScopeGrantedTrigger: SlidesExtensionPoint? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SlidesAddOnManifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SlidesAddOnManifest().with { $0.homepageTrigger = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let homepageTrigger = CodingKeys(stringValue: "homepageTrigger")
    static let onFileScopeGrantedTrigger = CodingKeys(stringValue: "onFileScopeGrantedTrigger")

    static let _knownKeys: Set<Swift.String> = [
      "homepageTrigger",
      "onFileScopeGrantedTrigger",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.homepageTrigger = try container.decodeIfPresent(
      GoogleAppsScriptType.HomepageExtensionPoint.self, forKey: .homepageTrigger)
    self.onFileScopeGrantedTrigger = try container.decodeIfPresent(
      SlidesExtensionPoint.self, forKey: .onFileScopeGrantedTrigger)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.homepageTrigger, forKey: .homepageTrigger)
    try container.encodeIfPresent(
      self.onFileScopeGrantedTrigger, forKey: .onFileScopeGrantedTrigger)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.slides.SlidesAddOnManifest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
